version: "3.5"
services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_hw2.2
    volumes:
      # - ./hw2.2:/var/lib/postgresql/data
      - ./sql/biblioteka.sql://docker-entrypoint-initdb.d/biblioteka.sql
    ports:
      - 5434:5432